r"""q4_1 GEMV on the NPU from phlegm's pool-order chunks: y[N] = W[N,K] @ x[K].

Phase 1 of .claude/plans/open-kernels-feasibility.md: the first real compute
kernel, checked against the pool bytes FLM's closed kernel consumes (which are
themselves verified byte-exact against C:/caps captures in pools.rs).

Dataflow (after vegah/LLMNpuTest granite_gemv, Apache-2.0): n_cores workers,
each fed its contiguous slice of bands by its own shim stream in elements of
PER_CALL chunks (double-buffered in L1); x broadcast once through one fifo; each
core emits one 64-float result object per band.

Build (WSL):  python build_design.py designs/gemv_q4/gemv_q4.py
Run (Win):    open-qwen-npu npu designs/gemv_q4/run.cfg   (see make_test.py)
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np
from ml_dtypes import bfloat16

import aie.iron as iron
from aie.iron import CompileTime, In, ObjectFifo, Out, Program, Runtime, TaskGroup, Worker
from aie.iron.controlflow import range_
from aie.iron.kernel import ExternalFunction
from aie.helpers.taplib import TensorTiler2D
from aie.utils import config

HERE = Path(__file__).parent

TILE_BYTES = 5120
BAND_ROWS = 64

# ---- the shape this build is specialised to; default = L0 linear_attn.qkv_proj
# [8192, 2048]. Override with env GEMV_N / GEMV_K / GEMV_CORES (make_test.py
# prints the matching build command per region).
N = int(os.environ.get("GEMV_N", 8192))
K = int(os.environ.get("GEMV_K", 2048))
N_CORES = int(os.environ.get("GEMV_CORES", 8))
PER_CALL = 4          # 4 x 5120 = 20480 B per element, x2 buffered -> 40 KB of L1


def _include_dirs() -> list[str]:
    from aie.iron.kernels._common import _detect_arch, _include_dirs as base

    inc = base()
    root = Path(config.cxx_header_path()) / "aie_kernels"
    inc.append(str(root))
    inc.append(str(root / _detect_arch()))
    return inc


def ensure_entry_points(n_entry: int, per_call: int, per_band: int) -> list[Path]:
    """One .cc per entry point (IRON compiles the source once per ExternalFunction;
    several entry points in one TU would each define every symbol)."""
    out = []
    for i in range(n_entry):
        p = HERE / f"gemv_q4_p{per_call}b{per_band}_k{i}.cc"
        src = (
            f"// GENERATED by gemv_q4.py: band chunk group {i} "
            f"(chunks {i * per_call}..{(i + 1) * per_call - 1} of a {per_band}-chunk band).\n"
            f"#define GEMV_PER_CALL {per_call}\n"
            f"#define GEMV_PER_BAND {per_band}\n"
            f'#include "gemv_q4.h"\n\n'
            f'extern "C" {{\n'
            f"GEMV_Q4_ENTRY({i})\n"
            f"}}\n"
        )
        if not p.is_file() or p.read_text(encoding="utf-8") != src:
            p.write_text(src, encoding="utf-8", newline="\n")
        out.append(p)
    return out


@iron.jit(aiecc_flags=["--alloc-scheme=basic-sequential"])
def gemv_q4(w: In, x: In, y: Out, *, n: CompileTime[int], k: CompileTime[int],
            n_cores: CompileTime[int], per_call: CompileTime[int]):
    per_band = k // 128                    # chunks per 64-row band
    n_entry = per_band // per_call
    assert per_band % per_call == 0
    bands = n // BAND_ROWS
    assert bands % n_cores == 0
    bands_per_core = bands // n_cores
    band_bytes = per_band * TILE_BYTES
    call_bytes = per_call * TILE_BYTES

    srcs = ensure_entry_points(n_entry, per_call, per_band)
    elem_ty = np.ndarray[(call_bytes,), np.dtype[np.uint8]]
    x_ty = np.ndarray[(k,), np.dtype[bfloat16]]
    acc_ty = np.ndarray[(BAND_ROWS,), np.dtype[np.float32]]
    w_ty = np.ndarray[(bands * band_bytes,), np.dtype[np.uint8]]
    y_ty = np.ndarray[(n,), np.dtype[np.float32]]

    kernels = [
        ExternalFunction(
            f"gemv_q4_p{per_call}b{per_band}_k{i}",
            source_file=str(srcs[i]),
            arg_types=[elem_ty, x_ty, acc_ty],
            include_dirs=_include_dirs(),
        )
        for i in range(n_entry)
    ]

    of_w = [ObjectFifo(elem_ty, name=f"w{c}", depth=2) for c in range(n_cores)]
    of_y = [ObjectFifo(acc_ty, name=f"y{c}", depth=2) for c in range(n_cores)]
    of_x = ObjectFifo(x_ty, name="x", depth=1)      # one activation, broadcast

    def core_body(win, xin, yout, *ks):
        xe = xin.acquire(1)
        for _ in range_(bands_per_core):
            ye = yout.acquire(1)
            for fn in ks:
                we = win.acquire(1)
                fn(we, xe, ye)
                win.release(1)
            yout.release(1)
        xin.release(1)

    workers = [
        Worker(core_body,
               fn_args=[of_w[c].cons(), of_x.cons(), of_y[c].prod(), *kernels],
               stack_size=0xD00)
        for c in range(n_cores)
    ]

    w_taps = TensorTiler2D.simple_tiler((1, bands * band_bytes), (1, bands_per_core * band_bytes))
    y_taps = TensorTiler2D.simple_tiler((1, n), (1, bands_per_core * BAND_ROWS))

    def sequence(a_w, a_x, c_y, w_prods, x_prod, y_conss):
        tg = TaskGroup()
        x_prod.fill(a_x, group=tg)
        for c in range(n_cores):
            w_prods[c].fill(a_w, tap=w_taps[c], group=tg)
            y_conss[c].drain(c_y, tap=y_taps[c], wait=True, group=tg)
        tg.finish()

    rt = Runtime(sequence, [w_ty, x_ty, y_ty,
                            [f.prod() for f in of_w], of_x.prod(), [f.cons() for f in of_y]])
    return Program(iron.get_current_device(), rt, workers=workers).resolve_program()


DESIGN = gemv_q4
SPECIALIZE = {"n": N, "k": K, "n_cores": N_CORES, "per_call": PER_CALL}
